---
- name: print a message
  hosts: webserver
  tasks: 
    - name: printing hello world
      ansible.builtin.debug:
        msg: "Learning ansible"   #if you don't give any msg by default print "Hello world

    - name: Install nginx
      ansible.builtin.package:
       name: nginx
       state: present        
      become: true  #setting root access specific to this task  

    - name: starting the service
      ansible.builtin.service:
        name: nginx
        state: started
      become: true

  
