---
- name: variables
  hosts: webserver
  vars:
    PLAY: play1
  tasks:
  - name: task1 variables
    vars:
      TASK: task1
    ansible.builtin.debug:
      msg: "this is for {{ TASK }} and {{ PLAY }}"

  - name: task2
    ansible.builtin.debug:
      msg: "this is for {{ TASKS }} and {{PLAY}}"
    vars:
      TASKS: task2   

- name: prompting means taking input from the user
  hosts: webserver
  vars_prompt:
  - name: USERNAME
    prompt: "Enter your name buddy..!"
    private: true
  
  - name: PASSWORD
    prompt: "Enter password..!"

  tasks:
  - name: Displaying the data
    ansible.builtin.debug:
      msg: username is {{USERNAME}} and password entered is {{PASSWORD}} and it's not visible as it is private.
