---

- name: concept is loop
  hosts: webserver
  tasks:
  - name: looping
    ansible.builtin.debug:
      msg: "current thing is {{item}}"
    loop:
    - Hello
    - guru
    - premakosame  

  - name: looping with differen actions
    ansible.builtin.package:
      name: "{{item.name}}"   
      state: "{{item.state}}"
    loop:
    - {name: 'nginx', state: present}
    - {name: mysql, state: present}
    - {name: zip, state: absent}    